"""added users table

Revision ID: 0559b1fe5aa8
Revises: 70acc94421a3
Create Date: 2023-03-05 08:27:52.598053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0559b1fe5aa8"
down_revision = "70acc94421a3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("first_name", sa.String(length=80), nullable=False),
        sa.Column("last_name", sa.String(length=80), nullable=False),
        sa.Column("email", sa.String(length=120), nullable=False),
        sa.Column("password", sa.String(length=120), nullable=True),
        sa.Column("phone", sa.String(length=80), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("phone"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    # ### end Alembic commands ###
