"""added app table field

Revision ID: 90f04ec523a2
Revises: 0559b1fe5aa8
Create Date: 2023-03-05 09:36:41.013533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90f04ec523a2'
down_revision = '0559b1fe5aa8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verify',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=80), nullable=False),
    sa.Column('otp', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('verify')
    # ### end Alembic commands ###
